creation_rules:
  # specific files
  - path_regex: apps/external-dns/secret\.yaml$
    encrypted_regex: "^(.*password.*)$"
    pgp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6

  # general rules
  - path_regex: \.yaml$
    encrypted_regex: "^(data|stringData)$"
    pgp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
  - path_regex: \.yml$
    encrypted_regex: "^(data|stringData)$"
    pgp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
