apiVersion: v1
kind: Secret
metadata:
  name: adguard-configuration
  namespace: external-dns
type: Opaque
stringData:
  url: http://192.168.40.201
  user: parker
  password: ENC[AES256_GCM,data:+tPbzLNRG9H4ErWKxkc7YL79GGqTpTz+Pw3YuSmZqruK,iv:tWU31fMFLeBwdCh953vG6n8bEYj/gWHNTdJB3m5JFKg=,tag:Zfwu2vZG5gd8yAaMbExtSw==,type:str]
sops:
  lastmodified: "2025-09-27T23:17:26Z"
  mac: ENC[AES256_GCM,data:UcUj7fOziO1gZBKt6qJ3o9efCGLBizeVsPxCQ4f1aogXjjuns5ixXSE2pGzpeei2hdeLXjgt9NR21Wx/N5Xa4rXX7fdzuHKcwfnaf34JiVQ+2dXCZQaBTdh9lXalLWHKstJw8ooXJjM4Da1NLEAYHfGpNGODFcK+Ohsih6A7AvE=,iv:GFur32301JZAUBmyDKCAvDfXLoDi1GLkf4MAcNu6jE0=,tag:LvOE8Jls6rCDrFQAuJX0+g==,type:str]
  pgp:
    - created_at: "2025-09-27T23:17:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4D44demlMMu+gSAQdAPqsHCu/rPpYU7BRvnmKAvzFTzaWpmaU7vYHYqHYwT2ww
        1HU7Nzo0YgtwcIEXMH5mMhGL25R9TwqOuhfAy9I7IsgqcipuY32uJSg1SFtWcIg0
        1GgBCQIQfucXLd3kT2MK2z++vAgAo4q/iRBR9umdAufwheq0V16YiCSuG4/YD8da
        HUhgm9GSXUtA1JmhGCWbzQAeUJhG6If8ZgoHd82X99PwQmwDe704KiS2uhuU099e
        /UeMGzWZY1MifA==
        =3GVo
        -----END PGP MESSAGE-----
      fp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
  encrypted_regex: ^(.*password.*)$
  version: 3.10.2
