apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 5m
  values:
    # External-DNS configuration
    provider: webhook

    # Domain filtering
    domainFilters:
      - home.lab

    # Sources to watch
    sources:
      - service
      - ingress

    # Webhook configuration
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --log-level=debug
      - --dry-run # will remove this to use the adguard webhook

    # Sidecar container for AdGuard webhook
    sidecars:
      - name: adguard-webhook
        image: nginx:alpine # Placeholder for now
        ports:
          - containerPort: 8888
            name: webhook
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf

    # Extra volumes
    extraVolumes:
      - name: nginx-config
        configMap:
          name: webhook-config

    # Create the ConfigMap
    extraObjects:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: webhook-config
          namespace: external-dns
        data:
          nginx.conf: |
            events {}
            http {
              server {
                listen 8888;
                location /healthz {
                  return 200 'OK';
                  add_header Content-Type text/plain;
                }
                location / {
                  return 200 '{"status": "placeholder webhook"}';
                  add_header Content-Type application/json;
                }
              }
            }
