apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 5m
  values:
    # Provider configuration
    provider: webhook

    # Domain filtering
    domainFilters:
      - home.lab

    # Sources to watch
    sources:
      - service
      - ingress

    # Extra args for external-dns
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --log-level=debug

    # AdGuard webhook sidecar
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: password
          - name: DRY_RUN
            value: "false"
