apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 5m
  values:
    domainFilters:
      - home.lab

    sources:
      - service
      - ingress

    extraArgs:
      - --log-level=debug

    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v9.1.0
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: password
          - name: DRY_RUN
            value: "false"
