apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: obsidian-livesync-couchdb
  labels:
    app: obsidian-livesync-couchdb
data:
  local.ini: |
    [chttpd]
    enable_cors = true
    bind_address = 0.0.0.0
    port = 5984

    [httpd]
    enable_cors = true

    [couchdb]
    single_node = true
    max_document_size = 50000000

    [cors]
    credentials = true
    origins = app://obsidian.md,capacitor://localhost,http://localhost

    [admins]
    parker = super-secret-password
