apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: obsidian-livesync-couchdb
  labels:
    app: obsidian-livesync-couchdb
data:
  local.ini: |
    [chttpd]
    enable_cors = true
    bind_address = 0.0.0.0
    port = 5984

    [httpd]
    enable_cors = true

    [couchdb]
    single_node = true

    [cors]
    credentials = true
    origins = *

    [admins]
    parker = super-secret-password
