apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
  namespace: obsidian-livesync-couchdb
data:
  local.ini: |
    [chttpd]
    require_valid_user = true
    enable_cors = true
    bind_address = 0.0.0.0
    port = 5984

    [chttpd_auth]
    require_valid_user = true

    [httpd]
    enable_cors = true

    [couchdb]
    single_node = true

    [cors]
    credentials = true
    origins = *
