apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
  namespace: obsidian-livesync-couchdb
type: Opaque
stringData:
  COUCHDB_USER: parker
  COUCHDB_PASSWORD: ENC[AES256_GCM,data:8pDYZn85qbM0mjXeqlOHf83Ab+7NLV523vUC0d7VnD+y,iv:uZktZ910L0qUlhdSLJKeAM6xFc3kDtBCtMlrcJggtis=,tag:s0iegpN7oThdXsn4Km81HQ==,type:str]
sops:
  lastmodified: "2026-03-08T20:13:38Z"
  mac: ENC[AES256_GCM,data:igV3p83B5xVor/dTS/fpSyy/Yarhpx+z0m/HdNEMSzux5iwGMsGbk7nzDU2ya2U4wcoPZEuayexBNeDCXuZFIoVLgtrRoQXJ9Qk8KoCcBZD20AF7I6/TeNkoD8GhmQidVj9hstjnikuz0p7PMEJqpnaApaQPofILDbC+a5HMrqg=,iv:nxV/2NE/sncB/u1ydC9Mi2T7gZHqW4HAVsJbV2If4ZM=,tag:6iSUC+Ankel6WbBscgIIgQ==,type:str]
  pgp:
    - created_at: "2026-03-08T20:13:38Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4D44demlMMu+gSAQdAll5/6aZMA+zwbQK/dXNfWrS695DFjyVgB2Q9SCEmO2Uw
        1kbYTI29d3K7ktw7jdJq/Ps8VQUo0hp2uqHFvlXBqoZfFMuNZ9kKi7pVz+Gdeo+B
        1GgBCQIQXI8xURudWauHhzUk2COZrhFeedC/S84WOInJfZsvDK9PNGzlvrnz2v4E
        pdtUubhElhVD4rr+gvSTmshp5oUq5Uje41d3frtOwKfGeyJGQNyN/p9936O6IEmY
        IZ0vO1gUUwZPDQ==
        =aY4I
        -----END PGP MESSAGE-----
      fp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
  encrypted_regex: ^(.*COUCHDB_PASSWORD.*)$
  version: 3.10.2
