apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - couchdb-credentials.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc-config.yaml
  - pvc-data.yaml
  - service.yaml
