apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-config
  namespace: obsidian-livesync-couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
