apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-data
  namespace: obsidian-livesync-couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
