apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: obsidian-livesync-couchdb
  labels:
    app: obsidian-livesync-couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
