apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
  namespace: obsidian-livesync-couchdb
type: Opaque
stringData:
  COUCHDB_USER: parker
  COUCHDB_PASSWORD: ENC[AES256_GCM,data:kW/+Qr6D5F+klRCDV03j6sq1LPczaAlMW6fM7iafODIR,iv:QN/CA8Vfdw2JqxgtGEeQzFNxG4WUuytLODTB3isyVUY=,tag:71wPsKe8nisu/LVBwDjxGw==,type:str]
sops:
  lastmodified: "2026-03-08T20:02:59Z"
  mac: ENC[AES256_GCM,data:V6gtRUeg8DWPequvjgwhD/9u3WE4Jk/ReIgCLAGrI8s5J5xfiu6T7JvBuzuQMAE8kRg/kSlv1gpy+XLm0B1/ZZwcuXTU9sQhNurDFZYIaoCJuoYIIT8doVl6p/CE4ARRiK70e6K+FwT/FHaE3g2fYgmUteFaJAWGyWMHjX2NMyM=,iv:aS/7hjFaL7uKUDx5/X/M+9GwjDf/50YqNTv+t3OcJZg=,tag:SsEmjW2UFM/n/8OzXjxt9Q==,type:str]
  pgp:
    - created_at: "2026-03-08T20:02:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4D44demlMMu+gSAQdAm04HtDReoObRx2b1Kr49e6/anNKppz1CoJXsTyJiIwUw
        VJxx9/qS6zZjoZ94GM8Km7g/Wu5ii9Wo5tn/6OaersPiAaE2hRb8sPSTwBc1yUtt
        1GYBCQIQeOSdbzxatvCW5Hg1F/YcdM1UoViSN+h8n8S3RgVVIKRDRE868uemjeFg
        wMkO3eeF5zsr6Jd1KoBPm7ByoNkEP/jshGeOZjSN/zPP1cs3a8N4c55kyLIY1vOR
        WI487UnbjI4=
        =/bEa
        -----END PGP MESSAGE-----
      fp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
  encrypted_regex: ^(.*COUCHDB_PASSWORD.*)$
  version: 3.10.2
