apiVersion: v1
kind: Secret
metadata:
  name: couchdb-users
  namespace: obsidian-livesync-couchdb
  labels:
    app: obsidian-livesync-couchdb
type: Opaque
stringData:
  # In the format:
  # parker:somesecretpassword:obsidian-livesync
  # someuser:somesecretpassword:somedatabasetheyshouldbeabletoaccess
  users.conf: ENC[AES256_GCM,data:HPZlkEGzpgABdUgahoAAYileJd+m1SqjHO/nwcij34Qu9mFGVkpvRpFXkfImDdtWgEUljBuN,iv:/GrZSH/bRBm26tQrD7nE+5MaF2cHiyUw3STP3uIKFhk=,tag:kWuCLMwKgaWHNGvxwnRnuw==,type:str]
sops:
  lastmodified: "2026-04-08T00:02:33Z"
  mac: ENC[AES256_GCM,data:phVTLd9BWfB/YYSxg2TnoeXNUYa7eZlQMWcBNYMSPgh+IYIkg47HRbZJ91Ohk/vsAMvaZ9KzfIul2ZUbUMGth/UadWohFAQEEgjr30vvBzV8aJfocbELbeCJaC7dQzzjN05Koso/3QsOmEG8xypiWfJM15aUnZIytzfmjxeZFz8=,iv:fhd8DzsiAU6HrOYOi6IdvsmI4nFNsOxMrrlJ5mCE9yU=,tag:dKUhafdk3ZqC2LkD9qOG7Q==,type:str]
  pgp:
    - created_at: "2026-04-08T00:02:33Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4D44demlMMu+gSAQdAx+LalSP+TlLkZsxvGrfzOTkhNVwWxEHD6XnGB2/NPUcw
        lmvU1LoQCdI8Waa/BXuFVCRbcRTjYmxTporb2Frtt2UerL5N3wnfL1IHSV0N4fqS
        1GgBCQIQfkOu/eOT88vfKMdBVRkns+YiDcjkFtHciK5/vnG62Oik/thVjbg9yyck
        Fv+y0PWVdD6EYJoZBj27cH5U4Xap+7nKMXknitV/jIi5D+FBlIEietKBSLM6epac
        4JxdvTV1Gni+Ag==
        =j/Ns
        -----END PGP MESSAGE-----
      fp: 0B0AB6E6DFA207454D32AED712F9EDBB3FFB06A6
  encrypted_regex: ^(.*users.conf.*)$
  version: 3.10.2
